### ISSUE TITLE
Upgrade to latest Typescript version

### ISSUE THREAD

**Issue by ReneDrie** [hjeti/vue-skeleton#109]
Should/Can we upgrade to the latest Typescript version. I don't think there are any issues since I've done this in past projects.
The `seng-disposable-manager` has some dependancies on later implemented TS stuff, so might be good to just upgrade

**Comment by ThaNarie** [comment]
Should be fine. Did you test it (3.9 - latest) in an existing project already? (I have updated it to 3.8 in a project few weeks back, which seem to work just fine).

**Comment by ThijsTyZ** [comment]
Yes, upgrade it
