### ISSUE TITLE
Possibility to add Favicon webpack generator

### ISSUE THREAD

**Issue by nicofonseca** [hjeti/vue-skeleton#17]
Can the favicon generator be added?

I added it manually and it worked fine.

## package.json
`"favicons-webpack-plugin": "^0.0.7"`

## build/webpack.prod.conf.js
```javascript
const FaviconsWebpackPlugin = require('favicons-webpack-plugin')

new FaviconsWebpackPlugin({
  logo:path.resolve(__dirname, '../static/image/favicon.png'),
  prefix: config.build.versionPath + "static/favicons/icon-[hash]",
  emitStats: false,
  statsFilename: 'iconstats-[hash].json',
  persistentCache: false,
  inject: true,
  background: '#fff',
  title: '',
  icons: {
    android: true,
    appleIcon: true,
    appleStartup: false,
    coast: false,
    favicons: true,
    firefox: true,
    opengraph: true,
    twitter: true,
    yandex: true,
    windows: true
   }
})
```
😘 😘 😘 😘 😘

**Comment by ReneDrie** [comment]
Great idea, should this be in the normal webpack config? Since you might want to use this locally as well to see if it works.
I always want a favicon, even when developing =)

**Comment by hjeti** [comment]
Cool. I can add it as an optional plugin that you can enable in the config. I don't like that people are forced to add a favicon.

**Comment by jesse-mm** [comment]
We could also include a white image as favicon (as placeholder) by default.

**Comment by pigeonfresh** [comment]
I agree with hjeti

**Comment by ReneDrie** [comment]
Why wouldn't you want a (white) default favicon? It's better than nothing and you always need one

**Comment by pigeonfresh** [comment]
I’m just not keen on adding placeholder files to a repo. And it’s a small step to assuming we need other icons too. So I’m in favor of configuration. :)

**Comment by jesse-mm** [comment]
I like to have this configurable but in a way it's opt-out instead of opt-in. That one placeholder file won't hurt anybody ;).
