### ISSUE TITLE
.eslintignore - src/vendor/**/*js  not working

### ISSUE THREAD

**Issue by nicofonseca** [hjeti/vue-skeleton#18]
When i run the code **yarn prettify**, Eslint is not ignoring the vendor folder completely. I do not know if the problem is because I add one more folder.
src / vendor / gsap / ...

## .eslintignore
`build/*.js
bin/*.js
config/*.js
src/vendor/**/*.js
`

![screen shot 2017-10-04 at 2 04 17 am](https://user-images.githubusercontent.com/12025749/31160654-5f693504-a8a8-11e7-8d4a-81497ba42073.png)

**Comment by jesse-mm** [comment]
To solve this you can add `.prettierignore` file in your project root. Added a PR for this.

https://github.com/hjeti/vue-skeleton/pull/19/commits/a52a41ba9354498b4d9bdddb8b9d1241b319be01.
