### ISSUE TITLE
Remove optimized SVGs

### ISSUE THREAD

**Issue by pigeonfresh** [hjeti/vue-skeleton#2]
Currently both original and optimized SVGs are part of the files being committed. Can't the optimized SVGs be ignored?  This way the repo of your project stays clean from rendered/compiled files.

**Comment by ReneDrie** [comment]
I think we better commit both. Since the creation of the SVG's is a separate task "yarn svg".
If we exclude the optimized SVG's, all developers always have to run that task as well. And that just doesn't make sense. And we also don't want to include it in every dev task.

**Comment by jesse-mm** [comment]
What we could do is run the svg after a npm install is run. Maybe we can investigate to implement a pull-hook that checks if svgs are changed and run svg generation automatically. This way we could remove the optimized SVGs.

**Comment by hjeti** [comment]
Way too much work for a few kb in the repository.
