### ISSUE TITLE
" fatal: Not a git repository: '.git' " when using vue-skeleton as a subdir on a repository

### ISSUE THREAD

**Issue by gianko** [hjeti/vue-skeleton#24]
If the `vue-skeleton` is used in a subdirectory inside a git repository this error will show up when trying to commit.

```
husky > npm run -s precommit (node v7.0.0)

fatal: Not a git repository: '.git'

husky > pre-commit hook failed (add --no-verify to bypass)
```

**Comment by larsvanbraam** [comment]
@gianko You you can change the git directory in the package.json on line 22!
