### ISSUE TITLE
Override of publicPath is not working

### ISSUE THREAD

**Issue by gianko** [hjeti/vue-skeleton#25]
as `/config/index.js` example tried with:

`"dev": "cross-env NODE_ENV=development node build/dev-server.js -- --publicPath=/v/vue-skeleton/`

and 

`"dev": "cross-env NODE_ENV=development node build/dev-server.js --publicPath=/v/vue-skeleton/`

but `configManager.getVariable(VariableNames.PUBLIC_PATH)` was always `/`

**Comment by jesse-mm** [comment]
Did you try changing it here: https://github.com/hjeti/vue-skeleton/blob/master/build/webpack.base.conf.js#L16

**Comment by hjeti** [comment]
@gianko Why do you want to change the PUBLIC_PATH during development? It will probably break the dev server. Setting the public path is only possible when running the build command as stated in the example in the `config/index.js`: `npm run build -- --publicPath=/v/vue-skeleton/`. The PUBLIC_PATH for dev is hardcoded to '/'.

**Comment by gianko** [comment]
@hjeti I'm trying to build a Vue theme on top of WordPress
Already changed the hrm path on the dev-client.

So, the correct way should be hardcode it for Dev, but change it on Build. 
Right?

**Comment by hjeti** [comment]
Oke nice. Yes you can hardcode it in the dev config. If the build path is always the same then you can just update the `publicPath` (line 7) in `config/index.js`. If you have multiple environments you can override it during build with `npm run build -- --publicPath=/v/vue-skeleton/`.
