### ISSUE TITLE
componentImage is camel cased and stylelinter doesn't like it.

### ISSUE THREAD

**Issue by Zuyderwijk** [hjeti/vue-skeleton#32]
componentImage() is camel cased so style linter breaks. Should be component-image()

Expected "componentImage" to be "componentimage"   function-name-case

**Comment by ReneDrie** [comment]
Updated and fixed:
https://github.com/hjeti/vue-skeleton/commit/04745adc63402471e6bd04893e7d0aeb94dcf5df
