### ISSUE TITLE
Configure vue-specific linting

### ISSUE THREAD

**Issue by flut1** [hjeti/vue-skeleton#35]
Because vue is quite flexible, I think we can benefit from using linting rules specifically aimed at vue. Vuejs maintains their own eslint plugin:

https://github.com/vuejs/eslint-plugin-vue

I haven't looked into which rules/presets we should be using for this plugin. Any suggestions?

**Comment by hjeti** [comment]
Yes that will be a great addition.

Gianko already started to implement it a while ago and this morning he had it working with our component setup (3 files). So he made some good progress but there are still some issues to resolve. For example it will now throw prettier eslint errors in the .vue file.

**Comment by hjeti** [comment]
You can find it in feature/vue-lint
