### ISSUE TITLE
Improve constants in namespaced store modules

### ISSUE THREAD

**Issue by flut1** [hjeti/vue-skeleton#36]
If I understand correctly, we want our namespaced store modules to provide the following:

- A const for the namespace
- A const for the name of each mutation, action and getter
- An easy way to access the mutation, action, getter names prefixed with the namespace

I found the following structure to be useful to achieve this:

```
// the namespace itself
export const EntitiesNamespace = 'entities';

// action names
export const GET_COLLECTION = 'getCollection';
export const AUTOFETCH_COLLECTION_REFS = 'autoFetchCollectionRefs';
export const GET_ENTITY = 'getEntity';
// each action name prefixed with the namespace
export const EntitiesActions = { GET_COLLECTION, GET_ENTITY, AUTOFETCH_COLLECTION_REFS };

// mutation names
export const SET_COLLECTION_DATA = 'setCollectionData';
export const SET_ENTITY = 'setEntity';
// each mutation name prefixed with the namespace
export const EntitiesMutations = { SET_ENTITY, SET_COLLECTION_DATA };

// getter names
export const COLLECTION_ENTITIES = 'collectionEntities';
export const COLLECTION_FULL_ENTITIES = 'collectionFullEntities';
export const COLLECTION_TOTAL = 'collectionTotal';
// each getter name prefixed with the namespace
export const EntitiesGetters = {
  COLLECTION_ENTITIES,
  COLLECTION_TOTAL,
  COLLECTION_FULL_ENTITIES,
};

// this function will do the actual prefixing
prefixNamespace(EntitiesNamespace, EntitiesActions, EntitiesMutations, EntitiesGetters);

export default {
  namespaced: true,
  ...
};
```

It is technically possible to automatically build the objects for the prefixed constants based on the exports. The reason I create them statically first and then patch them afterwards with `prefixNamespace` is so our IDE can statically analyse the objects and understand the properties in them. 

What do you think about this approach? Once I have some time, I can submit a PR for this. If someone else wants to pick this up, feel free.

**Comment by flut1** [comment]
To elaborate on the usage inside your component, the following 2 usages are equivalent:

```
actions: mapActions(EntitiesNamespace, {
  getCollection: GET_COLLECTION,
})
```

```
actions: mapActions({
  getCollection: EntitiesActions.GET_COLLECTION,
})
```

**Comment by flut1** [comment]
Source for prefixNamespace:

```
export default function prefixNamespace(namespace, ...objects) {
  objects.forEach(obj => {
    Object.keys(obj).forEach(key => {
      obj[key] = `${namespace}/${obj[key]}`;
    });
  });
}
```

**Comment by hjeti** [comment]
Nice work. Looks way more complete than what we have at the moment. It still supports both ways (with namespace and without) so you can still use it with vuex-connect.

**Comment by flut1** [comment]
@hjeti  I created an alternative approach. This requires less typing, but it is certainly more "magic". Not sure if this is the way to go, but I think it's worth consideration

```
// module
const view = {
  namespaced: true,
  state: {
    modals: [],
  },
  mutations: {
    PUSH_MODAL(state, { type, props }) {
       ...
    },
    CLOSE_MODALS_OF_TYPE(state, { type }) {
       ...
    },
    CLOSE_TOP_MODAL(state) {
       ...
    },
  },
};

patchModule(view, 'view');

export default view;
```

```
// patchModule utility
function patchModule(config, namespace) {
  const module = cloneDeep(config);

  /* eslint-disable consistent-return */
  mergeWith(config, module, (objValue, srcValue, key) => {
    if (key === 'module') {
      return objValue;
    }

    if (typeof srcValue === 'function') {
      return key;
    }
  });
  /* eslint-enable consistent-return */

  config.namespace = namespace;
  config.namespaced = param => `${namespace}/${param}`;
  config.module = module;
}
```

```
// importing the module (in modules.js)
import view from './module/view';

export default {
   ...
   view: view.module,
   ...
};

// usage: without namespace argument
store.commit(view.namespaced(view.mutations.PUSH_MODAL), ...);
// usage: with namespace argument
mapMutations(view.namespace, { pushModal: view.mutations.PUSH_MODAL }),
```

What it does, is to move the module configuration to the `.module` property, and mutate the export itself to have string values instead of functions.

**Comment by hjeti** [comment]
@flut1 I like the first option more. It took me a while to understand what happened exactly. Everybody should be able to use it so I rather go for option that requires a bit more typing but is easier to understand.

**Comment by flut1** [comment]
@hjeti I completely agree. I just wanted to present it as an option but I think the first one is more readable too.

**Comment by petervdn** [comment]
No idea if it's helpful, but I have been using the following method for quite a while now. It's compact, webstorm can autocomplete all options in your store categorized by getters, mutations, actions (allowing you to easily explore your store on the go), and the resulting usage is (IMO) very clean and readable.

**setup:**
```js
// definitions
export const userStore = {
  mutations: {
    setName: null,
    setEmail: null,
  },
  actions: {
    loadUser: null,
  }
};

initStoreCommands(userStore, 'user');

// actual store
export default {
  namespaced: true,
  state: {
    name: null,
  },
  getters: {},
  mutations: {
    [userStore.local.mutations.setName]: (state, payload) => {
      state.name = payload;
    },
  },
  actions: {},
};
```

**Usage**
````js
// userStore object is fully autocompleted by webstorm
this.$store.commit(userStore.mutations.setName, 'John'); 

...mapActions({
  loadUser: userStore.actions.loadUser,
});
````
What `initStoreCommands` does is set the value of every key to that same key, prefixed with the namespace, and all of this is duplicated into a 'local' property where all values don't have the prefix (these props in 'local' are used in the store itself).

**Resulting object:**
````js
 {
  mutations: {
    setName: 'user/setName',
    setEmail: 'user/setEmail',
  },
  actions: {
    loadUser: 'user/loadUser',
  },
  local: {
    mutations: {
       setName: 'setName',
       setEmail: 'setEmail',
    },
    actions: {
      loadUser: 'loadUser',
    }
  }
};
````

**Comment by jesse-mm** [comment]
Can we choose a solution as the current one is not really great either...
