### ISSUE TITLE
vue-types / props as object literal

### ISSUE THREAD

**Issue by gianko** [hjeti/vue-skeleton#37]
Maybe stop using vue-types?

related: https://github.com/vuejs/eslint-plugin-vue/issues/389

**Comment by flut1** [comment]
In React linting, there is a similar rule that says you have to add proptypes for the props to work. In our previous react projects, we disabled that rule because typing is often too dynamic. Say for example you want to create a module to re-use some types:

```
// inputTypes module
const inputTypes = {
  value: string;
  disabled: { type: Boolean, default: false },
  // some other ones
}
```

```
// component module
export default {
  name: 'MyInputComponent',
  props: {
    ...inputTypes,
    someOtherProp: string,
  }
```

**Comment by hjeti** [comment]
Yes I agree that is why the rule is disabled in the vue-lint branch. Vue-types is more valuable than the rule in my opinion. So removing vue-types because of the rule is not a good idea.
