### ISSUE TITLE
Remove global component registration

### ISSUE THREAD

**Issue by flut1** [hjeti/vue-skeleton#38]
Currently we have a `component/index.js` module where you can globally register components. Even though this provide somewhat of a convenience, I think it's better to explicitly import components when we want to use them. This makes it clearer where the components come from.

Furthermore, this construction has caused circular dependency problems for me. When a component is imported this way and uses some constants from a vuex store module, these exports may be undefined at the moment the component module is parsed.

**Comment by hjeti** [comment]
It should only be used for simple components like the Icon component. You don't want to import it in every file where you use it. If others find it confusing as well we can remove it and maybe only register the Icon component globally as an exception.

**Comment by ThaNarie** [comment]
Maybe put a big warning / "use at own risk" explanation in the file, so people know what they are getting in to.

**Comment by flut1** [comment]
I agree, a warning and/or description of what it should be used for would be a good compromise
