### ISSUE TITLE
Use url-loader instead of svg-inline-loader

### ISSUE THREAD

**Issue by flut1** [hjeti/vue-skeleton#39]
The default loader for .svg is an `svg-inline-loader`. What is the reasoning behind this? This will inline the svg as an svg tag (so `<svg .... </svg>`)

The result of this is when you use an svg in your styling:
```
background-image: url('some-svg.svg');
```

The result will be an svg tag inside your css:
```
background-image: url('<svg .... </svg>');
```
Which is not valid syntax. If you do want to use the inline loader, I think it's a better to explicitly opt-in to it in your import:
```
import svgTag from '!!svg-inline-loader!./some-svg.svg';
```

**Comment by ThaNarie** [comment]
svg-inline-loader should only be used in JS/HTML, not in CSS:
https://github.com/webpack-contrib/svg-inline-loader/issues/22#issuecomment-244348663

**Comment by jesse-mm** [comment]
I've changed the loading mechanism, by default it now uses url-loader. For the Icon we use the inline-loader. The only thing which annoys me a bit is that for svgo we need to add a bunch of options as a long string. Any ideas how we could solve that?

**Comment by ThaNarie** [comment]
There is always a hacky workaround option where you can create a loader that proxies the inline+svgo loaders + settings... but that's hacky... I hope we can get oneOf to work.

**Comment by flut1** [comment]
I found this ticket regarding `resourceQuery` and context: webpack/webpack#5732
This seems to be merged into webpack 4, but I haven't been able to get it to work there either

**Comment by flut1** [comment]
@ThaNarie @jesse-mm  Managed to get it to work in webpack 4 with `oneOf`. In `Icon`, you need to use a webpack context as such:

```
const svgContext = require.context('asset/svg/?inline', false, /\.svg/);

export default {
  ...
  computed: {
    icon() {
      return svgContext(`./${this.name}.svg`);
    },
  },
  ...
}
```

As soon as we merge #41 we can use this

**Comment by jesse-mm** [comment]
@flut1 yeah this looks like proper solution! Awesome!
