### ISSUE TITLE
BundleAnalyzerPlugin takes up a lot of resources on prod builds

### ISSUE THREAD

**Issue by flut1** [hjeti/vue-skeleton#49]
We have the `BundleAnalyzerPlugin` enabled by default on prod builds. However, this may cause the build to consume a lot of memory or even crash (I just encountered this with a dev who was running Node v9). This is likely because it generates a stats file (`generateStatsFile: true`) which is a huge json file. This causes large memory consumption when node is trying to stringify the json. 

What we can do is configure the stats file not to include irrelevant information. Some options (like `source`) make the stats object very big. However, I think it's worth considering removing the bundle anlyzer from the prod builds. Most of the time we run a build, we don't check the analyzer output. Instead, when running the `yarn analyze` command we execute a build just for that purpose. It will make the analyze command significantly slower, but I think we use it less often than we do production builds.

**Comment by flut1** [comment]
To configure stats, we can pass `statsOptions` to `BundleAnalyzerPlugin`. The [documentation](https://github.com/webpack-contrib/webpack-bundle-analyzer#options-for-plugin) even suggests to remove sources as an example:
> For example you can exclude sources of your modules from stats file with `source: false` option.

**Comment by hjeti** [comment]
Fixed it by using the default setup. That is without stats file and I enabled it with a flag so by default it doesn't analyze.
