### ISSUE TITLE
Disable eslint on the dev server by default

### ISSUE THREAD

**Issue by jesse-mm** [hjeti/vue-skeleton#5]
We've implemented push pre-hooks that lints your files before pushing. It's kind of annoying when throwing errors when just fiddling with code. I think it feels a bit counterproductive. I'm suggesting to turn it off while runnning the dev server. And let the linting be done by the IDE.

**Comment by pigeonfresh** [comment]
+1

**Comment by hjeti** [comment]
It's very easy to disable/enable it in the project config. But maybe it's a good idea if we set the default value to false. If a developer wants to use the eslint/tslint loader he can enable it in a second in the config.

**Comment by hjeti** [comment]
made the change
