### ISSUE TITLE
Can and should we update to ES7?

### ISSUE THREAD

**Issue by ReneDrie** [hjeti/vue-skeleton#50]
Currently the target in the tslint is set to ES6. And for instance when you do in Typescript:
`[1,2,3].includes(value => value === 1)`
It will throw an arrow that it can't find the method includes on an Array. There is more about this in this issue:
https://github.com/Microsoft/TypeScript/issues/2340

Setting it to ES7/es2017 fixes this. But I'm not sure if there are other implications or stuff that might be going wrong then?

If that is the case, we can leave it like this.

**Comment by ThaNarie** [comment]
Shouldn't be an issue, babel will compile the ES7 output just fine :)
