### ISSUE TITLE
LodashModuleReplacementPlugin breaks Lodash functions in production build

### ISSUE THREAD

**Issue by larsvanbraam** [hjeti/vue-skeleton#53]
Currently when using one of the following Lodash functions:  **get**, **has** or **set** in your project they break  when running a production build. This is due to the webpack LodashModuleReplacementPlugin, which has a flag for allowing those methods, https://github.com/lodash/lodash-webpack-plugin.

Adding this to the`webpack.prod.conf.js` file should allow you to use those methods in your project!

```javascript
new LodashModuleReplacementPlugin({
  paths: true,
}),
```

**Comment by hjeti** [comment]
That is how the plugin works. It will make the bundle larger if you enable that flag by default and I don't think everybody uses those functions in their project. So maybe we can add some documentation so people know how to enable it if they use advanced lodash features.
