### ISSUE TITLE
Problems with updating to more recent Node, package versions; `gulp-util` usage

### ISSUE THREAD

**Issue by Jayjader** [hjeti/vue-skeleton#54]
Node 10 came out about a week ago.

Attempting to use Node10 in the vue-skeleton triggers an error with the `upath` node module: the version used by this project is not configured correctly to recognize Node10 as a valid version, and thus fails any attempt to, for example, build & run the local dev server.

Running `yarn upgrade` after having upgraded to Node10 fixes this (obviously), but also outputs a warning about `gulp-util`, with [this](https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5) Medium post linked.

Should this be taken care of in this project, or be left up to whoever builds their own project off of this one?

**Comment by hjeti** [comment]
No we don't use gulp util in our project so we don't have to take care of it.
