### ISSUE TITLE
Use webpack to load locale modules

### ISSUE THREAD

**Issue by flut1** [hjeti/vue-skeleton#58]
Currently we are loading locale files by putting jsons in the static folder and using a localeLoader function to load them from there. There is no reason these files can't be imported through webpack. This gives us all advantages of webpack bundling like using hash filenames for the locale files.

Generally speaking, we should not have _any_ files in the static folder. The static folder should only be used for assets that are impossible or impractical to go through webpack.

In my current project, the jsons are placed in `src/locale/` and the `getTranslation` function in `bootstrap.js` looks like so: 

```
function getTranslation({code}) {
  return import('./locale/' + code.toLowerCase() + '.json');
}
```

I noticed we also have a custom function that waits until the locales have loaded. Is there any reason not to use the `Vue.initI18nManager` function provided by `vue-i18n-manager`? See the note at the bottom of the [getting started](https://matteogabriele.gitbooks.io/vue-i18n-manager/content/getting-started.html) page.

**Comment by flut1** [comment]
@hjeti  I found the issue with loading. See ticket MatteoGabriele/vue-i18n-manager#37

**Comment by hjeti** [comment]
I tried the latest version and there are still some issues with loading. When I enter the website with another locale than the default locale it still resolves the promise too early (when the default locale is loaded). So I can implement the webpack loading but we cannot get rid of the custom logic.
