### ISSUE TITLE
Incorrectly set local NODE_ENV will end up running a server with prod settings

### ISSUE THREAD

**Issue by petervdn** [hjeti/vue-skeleton#6]
shouldnt this fix always be there? 
process.env.NODE_ENV = JSON.parse(config.dev.env.NODE_ENV);

**Comment by jesse-mm** [comment]
Maybe we should consider setting env based on which npm command you are running instead of relying on environment variable.

**Comment by hjeti** [comment]
I've hardcoded the NODE_ENV in the dev and build command so it can't be overridden by environment variables.
