### ISSUE TITLE
CSS global class compilation order

### ISSUE THREAD

**Issue by nicofonseca** [hjeti/vue-skeleton#64]
Hi HJ! :sparkles::sparkles:

I'm using global CSS classes to reuse styles in elements for example,
```
.overlay {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  z-index: 1;
}
```

The problem arises when I want to step on some of the rules since in dev the compilation order of the css is different than in production

<img width="273" alt="screen shot 2018-06-28 at 15 58 04" src="https://user-images.githubusercontent.com/12025749/42054931-18332c3c-7aec-11e8-9ce7-50aa76672794.png">

### Dev
<img width="323" alt="screen shot 2018-06-28 at 15 18 54" src="https://user-images.githubusercontent.com/12025749/42052990-b1364c58-7ae6-11e8-8b31-d9d4972f3d10.png">

### Prod (I put !important for it to work)
<img width="324" alt="screen shot 2018-06-28 at 15 20 05" src="https://user-images.githubusercontent.com/12025749/42053019-c5087968-7ae6-11e8-975b-d2032b0a2a5e.png">

Is there a way for the compilation order to be the same in dev as prod?

Besis! :heart:  :kiss: :kiss: :kiss:

**Comment by hjeti** [comment]
@nicofonseca Where do you define the .overlay class? I did a test and when I define the .overlay inside a file that is loaded by the screen.scss it works like a charm. The screen.scss is the file that is loaded first in webpack so it must contain all the base styles that can be overriden by the css of the components.

**Comment by hjeti** [comment]
@ReneDrie How do you fix those errors? By running another build?

**Comment by nicofonseca** [comment]
@hjeti I define it in the file screen.scss. But as @ReneDrie  said when you do the build the component css are before the screen.scss 😔 
What would be the correct way to use the global classes?

**Comment by pigeonfresh** [comment]
@nicofonseca does it happen every build?
Could you share your import structure? Because I can't reproduce it at this moment and I'm tried overwriting my local class at several places in my scss.

**Comment by pigeonfresh** [comment]
@nicofonseca Could it be that you utils.scss somehow imports the stylesheet with global styles? Try and disable the all of the imports in utils.scss and try again. I was able to reproduce the issue when I import the global styles in utils.

**Comment by nicofonseca** [comment]
@pigeonfresh Ok, I'm going to try that and I'll let you know. Thanks! 😄

**Comment by pigeonfresh** [comment]
@nicofonseca any updates?

**Comment by nicofonseca** [comment]
Sorry for the delay! I have found the problem, but I guess this arises in older versions of the skeleton (I have the 1.2.4) in the new ones I did the same procedure and it works correctly. I had created my own normalize in addition to importing the normalize of node_modules, for some reason this did not like it since they contained the same file name, I had deleted everything in my file normalize thinking that the problem came from there but not , everything is fixed when I change my file name for example "normalize2".

I do not know if that would be the real problem or there are other things that make it work that way, but I could come up with that solution.

Thanks @hjeti @pigeonfresh @ReneDrie ! 😃

**Comment by nicofonseca** [comment]
**Updated!**

It has nothing to do with normalize, but at a certain point, yes. 
In version 1.2.4 when I import normalize and my files something happens on the build. 
For example, I have the following structure:

> style/base/main.scss
> style/helper/normalize-base.scss

And when I import them in **screen.scss** something happens and generates the inverted order.
I solved it importing everything I have in **base/main.scss** directly into **screen.scss** or by deleting the normalized call.

I don’t know if this is the main issue but I tried a lot of things and I believe the issue is related with imports. On version  1.3 or higher this doesn’t happen anymore.

I attached my style structure in case it helps.

[style.zip](https://github.com/hjeti/vue-skeleton/files/2173155/style.zip)
[HomePage.zip](https://github.com/hjeti/vue-skeleton/files/2173174/HomePage.zip)
