### ISSUE TITLE
Dist folder after build 

### ISSUE THREAD

**Issue by tktpro** [hjeti/vue-skeleton#68]
Why ./src/assets/image and ./src/assets/font not copied in dist folder when we make build?

**Comment by ThaNarie** [comment]
Everything in `src` will be handled by webpack, and either inlined or copied to the appropriate folder depending on the specific loader config.

Files that go outside of the webpack build (e.g. referenced in json files or in the index.html) should be placed in the `static` or `staticRoot` folders, which will be copied over to the build folder as-is.

**Comment by tktpro** [comment]
I have fonts in assets folder and connect them in .scss files, so how can i get them in dist folder? Or should i put it in static folder ?

**Comment by flut1** [comment]
Assets that you use in your .scss files should automatically be copied over to the output (dist) folder. They might be renamed by Webpack. If the assets are small they might be inlined into another JS file. If you want to test if the fonts are loaded correctly after you run a build, you can use the `preview` script  included in this skeleton (run `npm run preview` or `yarn preview`)

**Comment by tktpro** [comment]
That is the problem, webpack not copying fonts folder from assets to dist folder. Tried  checking by 'yarn preview'. [
![image 2](https://user-images.githubusercontent.com/8548887/43463071-658b78aa-94e0-11e8-97dc-56c100e7bd19.png)
](url)

**Comment by ThaNarie** [comment]
How are you referencing the font in the scss file?

**Comment by tktpro** [comment]
From this path \src\asset\style\util
![image 3](https://user-images.githubusercontent.com/8548887/43467296-17274a04-94ea-11e8-91c5-a933996e67ae.png)

**Comment by hjeti** [comment]
You load the fonts in a way webpack doesn't understand it. All the paths should be relative but it is even easier to use the font-face mixin of seng-scss. When you use it you don't have to care about paths and webpack will automatically understands the paths and processes the font files in the correct way. 

```scss
@include font-face('fontDinBlack', 'din', 'din_black', 900);
``` 

Also please move all font includes to a seperate file and import it in the screen.scss. The utils.scss and child files shouldn't output any css, because the file is automatically imported in every other scss file.

**Comment by tktpro** [comment]
Thanks! I connected font-face via seng-scss and it works. Also changed $pathComponentImage: 'asset/image'; to '../image'.  And all images now copying to dist folder. Problem was that I used this path from 'vue-skeleton/src/asset/style/util/_variable.scss',
