### ISSUE TITLE
Add/Use a Base SCSS structure

### ISSUE THREAD

**Issue by ReneDrie** [hjeti/vue-skeleton#7]
There are a couple of resets/base CSS functionality that I'm copying in each new project that I think should/could be easily included in the project.

I've create a branch "feature/base-scss" where I've added a simple reset (box-sizing, headings, paragraphs, lists).
Besides that I included folders for project specific "functions" and "mixins". Where we can place those that are specific for each project.

With this branch I'm just providing my opinion on how this could be. So please include you're suggestions.
The reason for this is that I think it would be good if there is a similar approach on base styling within each project.

The base can also include global copy styling. Which I think is really helpfull.

**Comment by jesse-mm** [comment]
I
