### ISSUE TITLE
Issue: Update GSAP to v. 2.0.2

### ISSUE THREAD

**Issue by nicofonseca** [hjeti/vue-skeleton#75]
Please update GSAP to version 2.0.2, because in SAFARI 11 doesn't work.

This is the issue:
https://github.com/greensock/GreenSock-JS/releases/tag/2.0.2
> - FIXED: changed "const" to "var" in ES module files for better compatibility with older browsers (like IE and Safari).

Besis 💋

**Comment by hjeti** [comment]
Updated the dependencies of Vue skeleton
