### ISSUE TITLE
Device state tracker missing max-width in mediaqueries

### ISSUE THREAD

**Issue by nicofonseca** [hjeti/vue-skeleton#84]
Heyyyyyyy!!! 

Please add X-SMALL mediaquery with max-width of 479px, because it's not working properly in small resolutions on the first load.

<img width="336" alt="screen shot 2018-11-07 at 15 22 41" src="https://user-images.githubusercontent.com/12025749/48151886-4335a000-e2a1-11e8-96d3-d9b04ba19612.png">

**Comment by ThaNarie** [comment]
What doesn't work properly, and why? :D

**Comment by nicofonseca** [comment]
As there is not a max-width set when you load the site on smaller resolutions the device state tracker returns undefined but then it works when you resize the browser.

<img width="226" alt="screen shot 2018-11-07 at 15 58 28" src="https://user-images.githubusercontent.com/12025749/48153861-0029fb80-e2a6-11e8-9c40-da2eecf021d5.png">

**Comment by ThaNarie** [comment]
@jesse-mm Maybe this is something in the DeviceStateTracker?

**Comment by hjeti** [comment]
I see now it doesn't match anything if your min width is smaller than 480. Will look into it.

**Comment by ReneDrie** [comment]
That’s indeed the case Hj. Discussed this with Jesse as well a while ago. The proposed fix is perfect I think
